2024-05-04 21:15:14: Route found: matched [/420dw3_07278_integration_project/api/users] with route [/420dw3_07278_integration_project/api/users]
2024-05-04 21:15:14: Controller: calling method Controllers\UserController::put().
2024-05-04 21:15:14: true
2024-05-04 21:15:14: RequestException: Bad request: required parameter [id] not found in the request.
	Stacktrace: #0 C:\xampp\htdocs\420dw3_07278_integration_project\private\src\GivenCode\Abstracts\AbstractController.php(53): Controllers\UserController->put()
		#1 C:\xampp\htdocs\420dw3_07278_integration_project\private\src\GivenCode\Domain\APIRoute.php(59): GivenCode\Abstracts\AbstractController->callHttpMethod(Object(GivenCode\Enumerations\HTTPMethodsEnum))
		#2 C:\xampp\htdocs\420dw3_07278_integration_project\private\src\GivenCode\Services\InternalRouter.php(55): GivenCode\Domain\APIRoute->route()
		#3 C:\xampp\htdocs\420dw3_07278_integration_project\private\src\Application\Application.php(25): GivenCode\Services\InternalRouter->route()
		#4 C:\xampp\htdocs\420dw3_07278_integration_project\index.php(15): Application\Application->run()
		#5 {main}
2024-05-04 21:15:50: Route found: matched [/420dw3_07278_integration_project/pages/users] with route [/420dw3_07278_integration_project/pages/users]
2024-05-04 21:15:50: true
2024-05-04 21:15:53: Route found: matched [/420dw3_07278_integration_project/api/users] with route [/420dw3_07278_integration_project/api/users]
2024-05-04 21:15:53: Controller: calling method Controllers\UserController::get().
2024-05-04 21:15:53: true
2024-05-04 21:15:54: Route found: matched [/420dw3_07278_integration_project/api/users] with route [/420dw3_07278_integration_project/api/users]
2024-05-04 21:15:54: Controller: calling method Controllers\UserController::put().
2024-05-04 21:15:54: true
2024-05-04 21:15:54: RequestException: Bad request: required parameter [userId] not found in the request.
	Stacktrace: #0 C:\xampp\htdocs\420dw3_07278_integration_project\private\src\GivenCode\Abstracts\AbstractController.php(53): Controllers\UserController->put()
		#1 C:\xampp\htdocs\420dw3_07278_integration_project\private\src\GivenCode\Domain\APIRoute.php(59): GivenCode\Abstracts\AbstractController->callHttpMethod(Object(GivenCode\Enumerations\HTTPMethodsEnum))
		#2 C:\xampp\htdocs\420dw3_07278_integration_project\private\src\GivenCode\Services\InternalRouter.php(55): GivenCode\Domain\APIRoute->route()
		#3 C:\xampp\htdocs\420dw3_07278_integration_project\private\src\Application\Application.php(25): GivenCode\Services\InternalRouter->route()
		#4 C:\xampp\htdocs\420dw3_07278_integration_project\index.php(15): Application\Application->run()
		#5 {main}
2024-05-04 21:17:11: Route found: matched [/420dw3_07278_integration_project/pages/users] with route [/420dw3_07278_integration_project/pages/users]
2024-05-04 21:17:11: true
2024-05-04 21:17:12: Route found: matched [/420dw3_07278_integration_project/api/users] with route [/420dw3_07278_integration_project/api/users]
2024-05-04 21:17:12: Controller: calling method Controllers\UserController::get().
2024-05-04 21:17:12: true
2024-05-04 21:17:14: Route found: matched [/420dw3_07278_integration_project/api/users] with route [/420dw3_07278_integration_project/api/users]
2024-05-04 21:17:14: Controller: calling method Controllers\UserController::put().
2024-05-04 21:17:14: true
2024-05-04 21:17:14: RuntimeException: Failure to update user id# [2].
	Caused by: PDOException: There is already an active transaction
	Stacktrace: #0 C:\xampp\htdocs\420dw3_07278_integration_project\private\src\Controllers\UserController.php(105): Services\UserService->updateUser(2, 'editor12', 'editor123', 'editor1@example...')
		#1 C:\xampp\htdocs\420dw3_07278_integration_project\private\src\GivenCode\Abstracts\AbstractController.php(53): Controllers\UserController->put()
		#2 C:\xampp\htdocs\420dw3_07278_integration_project\private\src\GivenCode\Domain\APIRoute.php(59): GivenCode\Abstracts\AbstractController->callHttpMethod(Object(GivenCode\Enumerations\HTTPMethodsEnum))
		#3 C:\xampp\htdocs\420dw3_07278_integration_project\private\src\GivenCode\Services\InternalRouter.php(55): GivenCode\Domain\APIRoute->route()
		#4 C:\xampp\htdocs\420dw3_07278_integration_project\private\src\Application\Application.php(25): GivenCode\Services\InternalRouter->route()
		#5 C:\xampp\htdocs\420dw3_07278_integration_project\index.php(15): Application\Application->run()
		#6 {main}
2024-05-04 21:18:03: Route found: matched [/420dw3_07278_integration_project/pages/users] with route [/420dw3_07278_integration_project/pages/users]
2024-05-04 21:18:03: true
2024-05-04 21:18:04: Route found: matched [/420dw3_07278_integration_project/api/users] with route [/420dw3_07278_integration_project/api/users]
2024-05-04 21:18:04: Controller: calling method Controllers\UserController::get().
2024-05-04 21:18:04: true
2024-05-04 21:18:07: Route found: matched [/420dw3_07278_integration_project/api/users] with route [/420dw3_07278_integration_project/api/users]
2024-05-04 21:18:07: Controller: calling method Controllers\UserController::put().
2024-05-04 21:18:07: true
2024-05-04 21:18:07: RuntimeException: Failure to update user id# [2].
	Caused by: PDOException: There is already an active transaction
	Stacktrace: #0 C:\xampp\htdocs\420dw3_07278_integration_project\private\src\Controllers\UserController.php(106): Services\UserService->updateUser(2, 'editor12', 'editor123', 'editor1@example...')
		#1 C:\xampp\htdocs\420dw3_07278_integration_project\private\src\GivenCode\Abstracts\AbstractController.php(53): Controllers\UserController->put()
		#2 C:\xampp\htdocs\420dw3_07278_integration_project\private\src\GivenCode\Domain\APIRoute.php(59): GivenCode\Abstracts\AbstractController->callHttpMethod(Object(GivenCode\Enumerations\HTTPMethodsEnum))
		#3 C:\xampp\htdocs\420dw3_07278_integration_project\private\src\GivenCode\Services\InternalRouter.php(55): GivenCode\Domain\APIRoute->route()
		#4 C:\xampp\htdocs\420dw3_07278_integration_project\private\src\Application\Application.php(25): GivenCode\Services\InternalRouter->route()
		#5 C:\xampp\htdocs\420dw3_07278_integration_project\index.php(15): Application\Application->run()
		#6 {main}
2024-05-04 21:18:14: Route found: matched [/420dw3_07278_integration_project/api/users] with route [/420dw3_07278_integration_project/api/users]
2024-05-04 21:18:14: Controller: calling method Controllers\UserController::get().
2024-05-04 21:18:14: true
2024-05-04 21:18:16: Route found: matched [/420dw3_07278_integration_project/api/users] with route [/420dw3_07278_integration_project/api/users]
2024-05-04 21:18:16: Controller: calling method Controllers\UserController::put().
2024-05-04 21:18:16: true
2024-05-04 21:18:16: RuntimeException: Failure to update user id# [3].
	Caused by: PDOException: There is already an active transaction
	Stacktrace: #0 C:\xampp\htdocs\420dw3_07278_integration_project\private\src\Controllers\UserController.php(106): Services\UserService->updateUser(3, 'editor22', 'editor123', 'editor2@example...')
		#1 C:\xampp\htdocs\420dw3_07278_integration_project\private\src\GivenCode\Abstracts\AbstractController.php(53): Controllers\UserController->put()
		#2 C:\xampp\htdocs\420dw3_07278_integration_project\private\src\GivenCode\Domain\APIRoute.php(59): GivenCode\Abstracts\AbstractController->callHttpMethod(Object(GivenCode\Enumerations\HTTPMethodsEnum))
		#3 C:\xampp\htdocs\420dw3_07278_integration_project\private\src\GivenCode\Services\InternalRouter.php(55): GivenCode\Domain\APIRoute->route()
		#4 C:\xampp\htdocs\420dw3_07278_integration_project\private\src\Application\Application.php(25): GivenCode\Services\InternalRouter->route()
		#5 C:\xampp\htdocs\420dw3_07278_integration_project\index.php(15): Application\Application->run()
		#6 {main}
2024-05-04 21:18:23: Route found: matched [/420dw3_07278_integration_project/pages/users] with route [/420dw3_07278_integration_project/pages/users]
2024-05-04 21:18:23: true
2024-05-04 21:18:25: Route found: matched [/420dw3_07278_integration_project/api/users] with route [/420dw3_07278_integration_project/api/users]
2024-05-04 21:18:25: Controller: calling method Controllers\UserController::get().
2024-05-04 21:18:25: true
2024-05-04 21:18:27: Route found: matched [/420dw3_07278_integration_project/api/users] with route [/420dw3_07278_integration_project/api/users]
2024-05-04 21:18:27: Controller: calling method Controllers\UserController::put().
2024-05-04 21:18:27: true
2024-05-04 21:18:27: RuntimeException: Failure to update user id# [2].
	Caused by: PDOException: There is already an active transaction
	Stacktrace: #0 C:\xampp\htdocs\420dw3_07278_integration_project\private\src\Controllers\UserController.php(105): Services\UserService->updateUser(2, 'editor12', 'editor123', 'editor1@example...')
		#1 C:\xampp\htdocs\420dw3_07278_integration_project\private\src\GivenCode\Abstracts\AbstractController.php(53): Controllers\UserController->put()
		#2 C:\xampp\htdocs\420dw3_07278_integration_project\private\src\GivenCode\Domain\APIRoute.php(59): GivenCode\Abstracts\AbstractController->callHttpMethod(Object(GivenCode\Enumerations\HTTPMethodsEnum))
		#3 C:\xampp\htdocs\420dw3_07278_integration_project\private\src\GivenCode\Services\InternalRouter.php(55): GivenCode\Domain\APIRoute->route()
		#4 C:\xampp\htdocs\420dw3_07278_integration_project\private\src\Application\Application.php(25): GivenCode\Services\InternalRouter->route()
		#5 C:\xampp\htdocs\420dw3_07278_integration_project\index.php(15): Application\Application->run()
		#6 {main}
